# Generated by Django 5.2.6 on 2025-09-16 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('medidas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(choices=[('banheiro', 'Banheiro'), ('sala_estar', 'Sala de Estar'), ('sala_jantar', 'Sala de Jantar'), ('escritorio', 'Escritório'), ('cozinha', 'Cozinha')], default='sala_estar', max_length=20)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
